# Generated by Django 5.1.5 on 2025-01-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.CharField(choices=[('User', 'User'), ('Farmer', 'Farmer'), ('Buissnessman', 'Buissnessman')], default='User', max_length=20),
        ),
    ]
