# Generated by Django 5.1.5 on 2025-02-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_users_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='addyourcrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropName', models.CharField(max_length=100)),
                ('cropestimatedprice', models.IntegerField()),
                ('cropgrade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='B', max_length=10)),
                ('croptotalweight', models.IntegerField()),
                ('cropdescription', models.CharField(max_length=200)),
                ('cropimages', models.ImageField(upload_to='')),
            ],
        ),
    ]
