# Generated by Django 5.1.5 on 2025-02-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0003_addyourcrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addyourcrop',
            name='cropimages',
            field=models.ImageField(upload_to='crop_images/'),
        ),
    ]
