# Generated by Django 5.1.5 on 2025-02-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0004_alter_addyourcrop_cropimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addyourcrop',
        ),
    ]
