# Generated by Django 5.1.5 on 2025-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0006_addyourcrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='addyourcrop',
            name='bidclosestime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='addyourcrop',
            name='bidstatus',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='addyourcrop',
            name='currentbidamount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addyourcrop',
            name='totalPrice',
            field=models.IntegerField(null=True),
        ),
    ]
