# Generated by Django 5.1.5 on 2025-03-02 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriapp", "0007_addyourcrop_bidclosestime_addyourcrop_bidstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addyourcrop",
            name="bidclosestime",
            field=models.DurationField(default=datetime.timedelta(days=3)),
        ),
    ]
