# Generated by Django 5.1.5 on 2025-03-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriapp", "0008_alter_addyourcrop_bidclosestime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addyourcrop",
            name="bidclosestime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
