# Generated by Django 5.1.5 on 2025-03-02 08:11

import agriapp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriapp", "0010_alter_addyourcrop_bidclosestime"),
    ]

    operations = [
        migrations.AddField(
            model_name="addyourcrop",
            name="cropaddedat",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="addyourcrop",
            name="bidclosestime",
            field=models.DateTimeField(
                default=agriapp.models.addyourcrop.get_bidclosestime_plus_72, null=True
            ),
        ),
    ]
