# Generated by Django 5.1.5 on 2025-07-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0011_addyourcrop_cropaddedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(choices=[('User', 'User'), ('Farmer', 'Farmer'), ('Businessman', 'Businessman')], default='User', max_length=20),
        ),
    ]
