# Generated by Django 5.1.5 on 2025-07-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0012_alter_users_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('businessman', models.ForeignKey(limit_choices_to={'usertype': 'Businessman'}, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='agriapp.users')),
                ('crop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriapp.addyourcrop')),
            ],
        ),
    ]
