# Generated by Django 5.1.5 on 2025-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0013_businessbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbid',
            name='bid_statusforbusinessman',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='TBD', max_length=20),
        ),
        migrations.AlterField(
            model_name='addyourcrop',
            name='cropgrade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=10),
        ),
    ]
