# Generated by Django 5.1.5 on 2025-07-31 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0014_businessbid_bid_statusforbusinessman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbid',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriapp.users'),
        ),
        migrations.CreateModel(
            name='resetpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('resetuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriapp.users')),
            ],
        ),
    ]
