# Generated by Django 5.1.5 on 2025-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0015_alter_businessbid_businessman_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbid',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
