# Generated by Django 5.1.5 on 2025-11-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0017_userfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='stars',
            new_name='rating',
        ),
    ]
