# Generated by Django 5.1.5 on 2025-11-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0018_rename_stars_userfeedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
