# Generated by Django 5.1.5 on 2025-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0019_remove_userfeedback_user_userfeedback_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='usertype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
