# Generated by Django 5.1.5 on 2025-11-21 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0020_userfeedback_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='usertype',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agriapp.users'),
        ),
    ]
